# Generated by Django 5.1.3 on 2024-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
