# Generated by Django 5.1.3 on 2024-12-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_mahasiswa_jenis_kelamin_mahasiswa_tgl_lahir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('kode', models.CharField(max_length=10, null=True)),
                ('sks', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'mata_kuliah',
                'verbose_name_plural': 'mata_kuliah',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=4, null=True)),
                ('semester', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'periode',
                'verbose_name_plural': 'periode',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, "Jum'at"), (6, 'Sabtu'), (7, 'Minggu')], null=True)),
                ('jam_mulai', models.TimeField(null=True)),
                ('jam_selesai', models.TimeField(null=True)),
                ('kuota_peserta', models.PositiveIntegerField(null=True)),
                ('dosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.dosen')),
                ('ruang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.ruang')),
                ('mata_kuliah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.matakuliah')),
                ('periode_akademik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.periode')),
            ],
            options={
                'verbose_name': 'kelas',
                'verbose_name_plural': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='KRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.mahasiswa')),
                ('periode_akademik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.periode')),
            ],
            options={
                'verbose_name': 'krs',
                'verbose_name_plural': 'krs',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.kelas')),
                ('krs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.krs')),
            ],
            options={
                'verbose_name': 'jadwal',
                'verbose_name_plural': 'jadwal',
            },
        ),
    ]
