# Generated by Django 5.1.3 on 2024-12-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_alter_matakuliah_options_alter_periode_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='matkul_prasyarat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.matakuliah'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ganjil'), (2, 'Genap')], null=True),
        ),
    ]
