# Generated by Django 5.1.3 on 2024-12-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_krs_jadwal_delete_jadwal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krs',
            old_name='periode_akademik',
            new_name='periode',
        ),
    ]
