# Generated by Django 5.1.3 on 2024-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_rename_periode_akademik_krs_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='KRS',
            field=models.ManyToManyField(blank=True, to='akademik.krs'),
        ),
    ]
