# Generated by Django 5.1.3 on 2024-12-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_kelas_krs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='KRS',
        ),
    ]
