# Generated by Django 5.1.3 on 2024-12-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_remove_kelas_krs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='periode_akademik',
            new_name='periode',
        ),
    ]
